services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: unless-stopped
    init: true
    ports:
      - "8000:8000"  # Django development server
    # env_file: ./.env  # Uncomment if .env file exists
    networks:
      - appnet
    depends_on:
      - postgres  # Ensure DB is ready before app starts

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: saas_inventory
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
    ports:
      - "5432:5432"  # PostgreSQL default port
    networks:
      - appnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saas_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
    # Persistent storage for PostgreSQL
