services:
  web:
    image: hasan082/inventory-app:latest
    ports:
      - "9001:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
    depends_on:
      - db

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
